name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md

jobs:
    integration:
        name: Continuous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Lint Code
              run: echo "Linting code..."

            - name: Run Tests
              run: echo "Running tests..."
    build-and-push-ecr-image:
      name: Build and Push ECR Image
      needs: integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Install Utilities
          run: |
            sudo apt-get update
            sudo apt-get install -y jq unzip
        
        - name: Configure AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        - name: Login to Amazon ECR
          id: ecr-login
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
            IMAGE_TAG: latest
          run: |
            # Build the docker container and push it to ECR
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "Image pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


